In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
diabetes = pd.read_csv(r"C:\Users\KIIT0001\Documents\GitHub\Mini_project_ML\required_files\Diabetes_dataset_cleaned.csv")
diabetes

,age,bmi,glucose_level,physical_activity_level,family_history,smoker,at_risk_diabetes
0,58,33.154816,71.049867,low,0,0,1
1,71,26.786882,125.964887,low,0,0,0
2,48,20.977319,61.876196,moderate,1,1,0
3,34,27.959924,137.648074,low,0,0,0
4,62,28.304175,65.879564,moderate,0,0,0
...,...,...,...,...,...,...,...
99989,74,28.001900,130.147993,low,0,0,0
99990,26,32.514707,141.784172,low,0,1,1
99991,71,26.504374,66.520077,moderate,0,0,0
99992,62,31.735351,105.753990,high,1,0,1


In [4]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [['low','moderate','high']]) 
# Encoding transformation applied(as 2D so [[]])
diabetes[['physical_activity_level']] = oe.fit_transform(diabetes[['physical_activity_level']]) 

In [5]:
diabetes.physical_activity_level.unique()

array([0., 1., 2.])

In [6]:
# converts our data from float type[0. ,1. , 2.] to integer
diabetes['physical_activity_level'] = diabetes['physical_activity_level'].astype(int)
diabetes.physical_activity_level.unique() 

array([0, 1, 2])

In [ ]:
# input output creation
ip = diabetes.drop('at_risk_diabetes',axis=1) #axis = 1 drops a column from input , axis = 0 drops row
op = diabetes.at_risk_diabetes # can also write diabetes[at risk diabetes]

# Training & Testing Split
# 80% training data , rest 20% testing data (test_siz=0.2)
# random_state used to fix the values otherwise everytime we run it takes different training and testing data 

from sklearn.model_selection import train_test_split

#prints number of training and testing samples
# x_train(input) and y_train(output) are the  samples used to train the model for input and output
# x_test used for prediction of output and that is compared with original output stored in y_test


(79995, 6)
(79995,)
(19999, 6)
(19999,)


In [12]:
from sklearn.ensemble import RandomForestClassifier

X = diabetes.drop("at_risk_diabetes", axis=1)
y = diabetes["at_risk_diabetes"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
rf = RandomForestClassifier(n_estimators = 100,random_state=42)
rf.fit(X_train,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [14]:
pred2 = rf.predict(X_test)
pred2


array([0, 0, 0, ..., 0, 0, 0], shape=(19999,))

In [15]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
print('Accuracy:',accuracy_score(y_test,pred2))
print('Recall:',recall_score(y_test,pred2))
print('Precision:',precision_score(y_test,pred2))
print('F1 Score:',f1_score(y_test,pred2))

Accuracy: 0.9111955597779889
Recall: 0.7461685823754789
Precision: 0.8131524008350731
F1 Score: 0.7782217782217782


In [26]:
import numpy as np

# Example feature values
age = 45
bmi = 30.5
glucose_level = 140
physical_activity_level =1
family_history = 1
smoking_status = 0

# Arrange features in the same order as training
features = np.array([[age, bmi, glucose_level, physical_activity_level, family_history, smoking_status]])

# Predict
single_prediction = rf.predict(features)

print("Predicted class:", single_prediction[0])


Predicted class: 1


C:\Users\KIIT0001\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [27]:
import pickle
pickle.dump(rf, open('random_forest_model.sav', 'wb'))
model_load = pickle.load(open('random_forest_model.sav', 'rb'))
